### PR TITLE
Added Kitchen tileset + add many objects

### PR DESCRIPTION
**Pull request by stickiedoesntanimate**

### CODE REVIEW

**Comment by AstrlJelly** [comment]
does this intentionally just change the one file..?

**Comment by stickiedoesntanimate** [comment]
QHAR!?!?!?!

**Comment by stickiedoesntanimate** [comment]
astrl can you merge this pretty please

**Comment by stickiedoesntanimate** [comment]
aaaaaaaaaaaaaaaaaa
hello korboy game discord
i have added estrogen
astrl please merge this

**Pull request merged**
